#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from nadamp import Amp

def main():

    HARMONY_IP='HarmonyHub'
    HARMONY_PORT=5222

    email = sys.argv[1]
    password = sys.argv[2]

    amp = Amp(HARMONY_IP, HARMONY_PORT, email, password)
    print amp.get_vol()

if __name__ == "__main__":
    main()
